module.exports={
    ADMIN_COLLECTION:'admin',
    PRODUCT_COLLECTION:'product',
    CATEGORY_COLLECTION:'category',
    USER_COLLECTION:'user',
    BAG_COLLECTION:'bag',
    ORDER_COLLECTION:'order',
    FAVORITE_COLLECTION:'favorite'
}